com.dwarfeng.fdr.jdbc.driver=com.mysql.cj.jdbc.Driver
com.dwarfeng.fdr.jdbc.url=jdbc:mysql://your-host-here:3306/fdr?serverTimezone=Asia/Shanghai&autoReconnect=true
com.dwarfeng.fdr.jdbc.username=root
com.dwarfeng.fdr.jdbc.password=your-password-here
com.dwarfeng.fdr.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
